[GLOBAL]
pants_version = "2.13.0"
# use_deprecated_cli_args_semantics = false
use_deprecated_directory_cli_args_semantics = false

backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
]



[python]
# This will become the default in Pants 2.15.
tailor_pex_binary_targets = false

[anonymous-telemetry]
enabled = false